//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.08 at 09:48:43 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservice.mum.edu/account", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.mum.wsdl.account;
